radius: 16
verticalRadius: 80
maxBases:
  default: 5 #Can be bypassed by the permission: "itemsorter.unlimitedBases"
  others: #permissions
    - "itemsorter.vip": 10
    - "itemsorter.vipplus": 20
    - "itemsorter.moderator": 100
orderChestContent: true # Sort filters after closing it (doesn't work with custom chest from AdvancedChests)
Language: "EN"
customsqlitelib: false # Use only if SQLite doesn't work in your machine.