radius: 16
verticalRadius: 80
maxBases:
  default: 5 #can be bypassed by the permission: "itemsorter.unlimitedBases"
  others: #permissions
    - "itemsorter.vip": 10
    - "itemsorter.vipplus": 20
    - "itemsorter.moderator": 100
orderChestContent: true
Language: "EN"
customsqlitelib: false